language: python
sudo: false

addons:
  apt_packages:
    - pandoc
    - texlive-full
    - texlive-xetex


install:
  - pip install tox

script:
  - tox -r

matrix:
    include:
      - python: 3.7
        env: TOXENV=style
        dist: xenial
        sudo: true

      - python: 3.7
        env: TOXENV=coverage
        dist: xenial
        sudo: true

      # - python: 3.7
      #   env: TOXENV=docs
      #   dist: xenial
      #   sudo: true
      - python: 3.7
        env: TOXENV=integration
        dist: xenial
        sudo: true

      - python: 3.7
        env: TOXENV=py37
        dist: xenial
        sudo: true

      - python: 3.8
        env: TOXENV=py38
        dist: xenial
        sudo: true

      - python: 3.9
        env: TOXENV=py39
        dist: xenial
        sudo: true






