[tool.black]
line-length = 79
target-version = ['py38']


[tool.pytest.ini_options]
addopts = "-m 'not integration'"
markers = [
    "ALL: All tests are marked with this marker",
    "integration: Integration tests",
    "deprecated_api: Uses the old coordinate based Python API",
    ]
testpaths = [
    "tests",
]
